### ISSUE TITLE
Build Number and Release Notes not taken into account

### ISSUE THREAD

**Issue by Juansero29** [akiojin/appcenter-distribute-github-action#51]
When using the runner it seems like it doesn't take into account the build number that I send.

Having the following YML for app center distribution doesn't set the correct build number into the distributed release.
```

      - name: Print GitHub Run Number
        shell: pwsh
        run: echo ${{ github.run_number }}
        
      - name: AppCenter Distribute GitHub action
        uses: akiojin/appcenter-distribute-github-action@v1.4
        with:
          token: ${{ secrets.APPCENTER_TOKEN }}
          build-number: ${{ github.run_number }}
          path: .\Nou\bin\Release\net7.0-android\publish\com.enigmatikreations.nou-Signed.aab
          app: juansero29/Nou
          mandatory: true
          silent: false
          group: "Collaborators"
          release_notes: ${{ github.event.inputs.message }}
```

For example, in this run the release number was 8, however you can see in the output the Release was still called `Release 1.0.10 (1)` and not `Release 1.0.10 (8)`.

![image](https://user-images.githubusercontent.com/19156405/205768461-7d40ac89-9bdc-4d32-a381-be049ce6b745.png)
